ver: 8
debug: false
#保存玩家IP，如果下次进入服务器时IP一致自动登录
AutoLogin: false
#注册确认行为
RegisterVerification: false
#防止死亡的玩家发送聊天和指令(防止某些情况假人测压能在未登陆的情况下发送聊天和指令
AntiDeathHandle: false
#无需登录的IP
#NoLoginIp: '127.0.0.1'

#注册后控制台执行指令
RegisteredCommands:
  - 'say %player% 已注册'

#登录后控制台执行指令
LoginCommands:
#  - ''

#新玩家加入时
NewPlayerJoin:
  #阻止新玩家(开启在线登录的情况下没必要启用这个)
  DisallowPlayer: false
  DisallowMessage: '阁下没有加入白名单'

#在线登录
Authenticate:
  enable: true
  #自定义登录顺序从上到下,使用正则匹配式
  #或者使用外置Yggdrasil登录地址
  #todo 目前已知这一段如果使用插件更新配置文件的功能后会被转义成成别的,导致正则失效.所以需要手动从默认配置里复制粘贴过来
  YggdrasilList:
    - pattern: '^mc\..*'   #mc开头的使用正版登录
      action: MOJANG
      default-allow: true          #默认允许
    - pattern: '^ls\..*'   #ls开头的使用LittleSkin登录
      action: 'https://mcskin.littleservice.cn/api/yggdrasil/sessionserver/session/minecraft/'
    - pattern: '^bs\..*'   #bs开头的使用Blessing登录
      action: 'https://skin.prinzeugen.net/api/yggdrasil/sessionserver/session/minecraft/'
    - pattern: '.*'          #其他使用离线登录
      action: OFFLINE
#使用代理
HttpProxy:
  Enable: false
  #[DIRECT,SOCKS,HTTP]
  Type: 'SOCKS'
  IP: '127.0.0.1'
  Port: 1080

#允许跨协议版本号
ViaVersion:
#- 735 #1.16
#- 736 #1.16.1
#- 751 #1.16.2
#- 753 #1.16.3
