name: MoeLogin
main: cn.whiteg.moeLogin.MoeLogin
version: '1.3.2'
api-version: 1.13
author: MoeWhite
depend: [MMOCore, MoePacketAPI]
softdepend: [MoeInfo]
commands:
  moelogin:
    description: The is MoeLogin Command
    aliases: ['ml']

  ban:
    description: The is MoeLogin Command

  premium:
    description: toggle Authenticate

  yggdrasil:
    description: set Yggdrasil S
